### ISSUE TITLE
extension vscode-pdf is not working correctly

### ISSUE THREAD

**Issue by Jay-Young** [coder/code-server#1691]
extesion `vscode-pdf` is not working correctly, opend pdf file is not display.

request fails with the following links:
https://mydomain.com/webview/vscode-resource/file///share/CACHEDEV1_DATA/.qpkg/qvscode/data/extensions/tomoki1207.pdf-0.6.0/lib/web/viewer.css
https://mydomain.com/webview/vscode-resource/file///share/CACHEDEV1_DATA/.qpkg/qvscode/data/extensions/tomoki1207.pdf-0.6.0/lib/pdf.css
https://mydomain.com/webview/vscode-resource/file///share/CACHEDEV1_DATA/.qpkg/qvscode/data/extensions/tomoki1207.pdf-0.6.0/lib/build/pdf.js
https://mydomain.com/webview/vscode-resource/file///share/CACHEDEV1_DATA/.qpkg/qvscode/data/extensions/tomoki1207.pdf-0.6.0/lib/build/pdf.worker.js
https://mydomain.com/webview/vscode-resource/file///share/CACHEDEV1_DATA/.qpkg/qvscode/data/extensions/tomoki1207.pdf-0.6.0/lib/web/viewer.js

the correct request link should be like:
https://mydomain.com/vscode-remote-resource?path=/share/CACHEDEV1_DATA/.qpkg/qvscode/data/extensions/tomoki1207.pdf-0.6.0/lib/web/viewer.css

I don't know whether the extension itself or code-server causes the error?

- Web Browser: Microsoft Edge 81.0.416.77
- Local OS: Windows 10 Pro x64 1909 18363.836
- Remote OS: QNAP QTS 4.4.2.1270 ( Linux 4.14.24-qnap x86_64 )
- `code-server --version`: 3.3.1

**Comment by nhooyr** [comment]
cc @code-asher

**Comment by code-asher** [comment]
I can confirm the same behavior when using Edge. Chrome and Firefox seem to load the file without a problem.

These `/webview` requests are a bit weird because they are intercepted by a service worker and then retrieved over the websocket so they don't need to resolve as regular http requests.

On Edge I'm getting 401 unauthorized errors. So maybe this interception mechanism doesn't work on Edge and it's trying to run them as regular HTTP requests?

Something else is broken here though because for me on Chrome and Firefox sometimes the files load and everything works and sometimes they load but give these errors:

```
TypeError: firstPagePromise is undefined viewer.js:1191:7
TypeError: this.toolbar is null viewer.js:1199:5
```

**Comment by nhooyr** [comment]
Yea sounds like a bug in Edge then.

**Comment by mboyar** [comment]
Similar problem still occurs on iPadOS 14.1 with Chrome 85.0.4183.109
