### ISSUE TITLE
Provide alternate image registry to dockerhub

### ISSUE THREAD

**Issue by onedr0p** [coder/code-server#3335]
Hello,

In order to combat dockerhub's imposed rate limits it would be great to host these images on ghcr or quay.io. Are there on any thoughts from the community on this initiation?

**Comment by onedr0p** [comment]
Not stale

**Comment by jsjoeio** [comment]
I don't imagine we'll do this because we want to keep maintenance overhead small but maybe someone else could publish an unofficial one?

**Comment by onedr0p** [comment]
I can't imagine it wouldn't be hard to do, GHCR is free and easy to push images to since you are already using GitHub workflows. There is no maintenance overhead IMO. Plus you get a shiney "Packages" link on the side of the repo with a direct link to the image.

See:
https://github.com/kube-vip/kube-vip which links to
https://github.com/kube-vip/kube-vip/pkgs/container/kube-vip

<3

**Comment by jsjoeio** [comment]
What are your thoughts @code-asher ?

**Comment by code-asher** [comment]
I like the idea especially since it is integrated into GitHub.

Can we just add two more tags using ghcr.io and that takes care of it?

https://github.com/coder/code-server/blob/cd78f32dc06f7f3ea518872df314b72f3cfafacd/ci/release-image/docker-bake.hcl#L16-L17

And maybe we have to use `docker/login-action` to log into ghcr.io as
well.  So basically a copy of this block:

https://github.com/coder/code-server/blob/cd78f32dc06f7f3ea518872df314b72f3cfafacd/.github/workflows/docker.yaml#L32-L36

Except with:

```
with:
  registry: ghcr.io
  username: ${{ github.actor }}
  password: ${{ secrets.GITHUB_TOKEN }}
```

I am not sure though, this is mostly just a guess.

**Comment by onedr0p** [comment]
That looks exactly like what needs to be done, though I am not familiar with the HCL fun going on there 😄

**Comment by jsjoeio** [comment]
Oh nice @code-asher! Okay @onedr0p if you want to do this, go for it. Otherwise, I'll add this for June 2022 when the time comes!

**Comment by onedr0p** [comment]
Done https://github.com/coder/code-server/pull/5187
