### ISSUE TITLE
create a code-server app optimized for android

### ISSUE THREAD

**Issue by Piposo** [coder/code-server#3370]
Many people who use this project are on their cell phones for the simple fact that if we had a pc we would be using vscode itself, there is an app called vheditor that uses this project, but it is not very optimized, we will not be able to create a version of this project for android ? we would love it if that were possible or create an app with the same functionality as vs code.

_Originally discussed in https://github.com/cdr/code-server/discussions/2840_

**Comment by bpmct** [comment]
Relaying some of my thoughts from #2840 here:

Currently, code-server has a PWA feature that makes any code-server instance appear as an app on a phone's home screen. 

In terms of hosting code-server itself:
- there cloud free providers such as Railway that can [host code-server](https://github.com/cdr/deploy-code-server), which can then be accessed on any device (including an Android/iOS phone)
- [code-server can also be hosted on Termux](https://wiki.termux.com/index.php?title=Node.js&mobileaction=toggle_view_mobile), but requires some setup, as you have to download the termux app and run some setup commands.


Are you looking for an app that does the following?
1. can be downloaded from Google Play
2. hosts code-server on the phone
3. starts code-server / has a webview of code-server when you open the app
4. can stop code-server on the Ui, or by closing, to save compute power
4. (optional): uses --link so that any device can also use code-server, but using your phone's compute
5. (i think you mentioned this): reduced features from existing VS Code/code-server for improved performance? Could you provide more details here?

If so, that would be pretty cool. Just trying to get a sense of the feature-set you are looking for.

One pitfall of #2, is I believe that many development workloads are still not supported without an underlying Linux environment, such as Termux. I also don't think it would be possible to run code-server without Termux on Android.

It looks like VHEditor includes Termux built-in. I am not sure if this is something we would do ourselves as the Termux app itself offers a lot of goodies. I think a tighter integration with Termux + instant PWA support could get us a lot of the way there, but want to make sure I'm understanding your request correctly @Piposo.

**Comment by Piposo** [comment]
well termux is a great terminal that we cannot deny, but if you really want to program using frameworks that need administrator permission it will not be possible because no cell phone,has root or administrator mode that gives you full access to the cell. the code-server itself is great but the terminal / termux is limited in itself, but I know a way to have a ubuntu terminal in termux. knowing this it would no longer be necessary to use the original termux, but to run the ubuntu terminal, it gives us administrator access to the projects, but again you do not have access to other local projects, only projects that were created in the ubuntu terminal, knowing that they could integrate the app to create a folder to create the projects and the users access. the idea is as follows:
1. create an application that can be used by android with an optimization and easy to find.
2. update the termux terminal so that after starting the code-server app it runs the ubuntu terminal and not termux.
3. have an on / off button to not consume too much of the user's battery.
4. an optimization in the text editor so you don't have to use an integrated keyboard on your cell phone or a virtual pc keyboard.
5. keep the code-server basics, be able to use extensions and the basics.
after all this keep the app optimized and in sync with the code server versions. that's my idea to help android developers.

**Comment by bpmct** [comment]
> but I know a way to have a ubuntu terminal in termux

are you referring to this specifically? https://github.com/Neo-Oli/termux-ubuntu or another resource? So this essentially allows someone to install packages that would previously be limited to root?

> an optimization in the text editor so you don't have to use an integrated keyboard on your cell phone or a virtual pc keyboard.

Can you clarify? Do you mean "make the on-screen keyboard functional for code-server without requiring an external one?"

 > keep the code-server basics, be able to use extensions and the basics.

Is there a reason why this couldn't be the full code-server app, maybe with some of the stuff from the sidebar simply "hidden"? (you can right-click and hide them by default)

**Comment by Piposo** [comment]
yes I was referring to that, I think that a limited thing but that was still the vs code and functional will be accepted

**Comment by GNUxeava** [comment]
>but I know a way to have a ubuntu terminal in termux


While it may solve some issues regarding the projects that require root privilege, it might still suffer from the same limitations faced by Termux (like inability to read /proc) since it basically runs proot on the newly installed rootfs (which is Ubuntu in your case)

htop on Termux:
![htop-on-termux](https://user-images.githubusercontent.com/21287366/118371372-f9dd0e80-b5c9-11eb-8dff-dddb93b34a9f.png) 
htop on Alpine on Termux:
![htop-on-alpine-on-termux](https://user-images.githubusercontent.com/21287366/118371409-2c870700-b5ca-11eb-92ae-777bf2cb3129.png)

**Comment by aleleba** [comment]
I think some hybrid application alternative like Ionic capacitor can be used to achieve this. But I feel honest I don't think it would be an alternative or the concept of code-server. Since what it raises is to have the same work environment in any place, and as discussed above, it can be achieved by installing the PWA. Currently I use it to program in android too, but I move to any device and keep my configurations, repositories, etc. And I only access either on windows, mac, Linux or Android. I think it would lose its sense of being to run it locally by code-server, since what it tries to solve is to work in several environments in a homogeneous way. But I think one way to achieve it, if you need to develop, can be with: https://capacitorjs.com/

I hope everyone has a good day :D

**Comment by Merith-TK** [comment]
Also look into `termux-chroot`, should come in the `proot` package, 
it spawns a shell where the `rootfs`, `/`, is actually pointing to `/data/data/com.termux/files/usr` while keeping some directories the same as needed
