### ISSUE TITLE
ngrok as an option for connecting to code-server remotely

### ISSUE THREAD

**Issue by minimaxir** [coder/code-server#3632]
[ngrok](https://ngrok.com/) is a more typical way of connecting to servers hosted at `localhost`, and I've verified it works with code-server.

Additionally, I've verified that ngrok allows iPad support of a hosted server without having to do self-cert shenanigans.

If it's worthwhile I can add information about this use case to the docs.

**Comment by janiversen** [comment]
I am not so sure about the “more typical”.
I have a self hosted code-server that I use on my ipad for several reasons but one being I do not want it exposed to the internet and available when I am offline. Ngrok would be a step backwards from that goal.

For services I want to have available remotely, I use ddns together with dmz. This means the traffic is direct once the weksocket is open and thus reduces latency.

I believe there are equal cases for using ngrok, so adding it as a further option can only be a good thing, since they have a free plan.

**Comment by minimaxir** [comment]
At the least, I'm planning a write-up on getting coding onto the iPad, and messing around with certs and/or DNS is a massive friction that will likely make prospective users give up on the process.

**Comment by jsjoeio** [comment]
If it helps, I made a video for [deploying code-server to Railway](https://www.youtube.com/watch?v=IWfkkaY5fXs).

But regardless, we would welcome any contributions to the docs! (There are so many ways to set up code-server for use on an iPad and it would be great to have guides for all of them).
