### ISSUE TITLE
Run as rootless container like it is allowed in Docker ver 20.10 and Podman

### ISSUE THREAD

**Issue by PavelSosin-320** [coder/code-server#3715]
Get rid Docker, server, and root user use. 
The gaps are:

1.  static config and workspace mount points in the Dockerfile as /config and /workspace. 
2. Don't use ~

**Comment by jsjoeio** [comment]
@PavelSosin-320 could you please elaborate on why you want these changes? Thank you!

**Comment by mirekphd** [comment]
Presumably because it is a standard practice in corporate clusters to avoid running containers as root. Platforms like Openshift and OKD will by default disallow running containers with elevated capabilities and even randomize runtime user IDs for containers. This has always restricted the choice of IDEs that are available in such environments.
> @PavelSosin-320 could you please elaborate on why you want these changes? Thank you!

**Comment by mirekphd** [comment]
Currrently most of the [entrypoint.sh](https://github.com/coder/code-server/blob/main/ci/release-image/entrypoint.sh) script requires root at runtime.

The main (and only justifiable for an IDE) reason for root here is the need to support `docker` in VS Code. Why not switch to `podman` which is rootless by design?

**Comment by DevDorrejo** [comment]
Hello, I am using podman rootless and the process is required to introduce sudo password of the user, but it won't accept the password and will fail with incorrect password.

**Comment by luckylinux** [comment]
I am running Podman as User `podman` with UID `1002` and GID `1002`.

Unfortunately there is no easy Way to get this working with Podman Rootless, not when already part of a Pod at least (unless all other Containers part of the Pod are fine with `UserNS` set).

The easiest is **if** the Container is NOT part of a Pod and/or there is **only** 1 Container in the Pod. In that Case it should be sufficient to set `UserNS=keep-id:uid=1002,gid=1002` in the `code-server.container` Quadlet.

I unfortunately found that with my Setup, I need to build a Custom Image 👎.

I also need to add `:U` to my bind-mounts which causes unfortunately to use SubUID/SubGID, even though I'm setting the User explicitely 👎.

Custom `passwd`:
```
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/run/ircd:/usr/sbin/nologin
_apt:x:42:65534::/nonexistent:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
podman:x:1002:1002:,,,:/home/coder:/bin/bash
```

Custom `group`:
```
root:x:0:
daemon:x:1:
bin:x:2:
sys:x:3:
adm:x:4:
tty:x:5:
disk:x:6:
lp:x:7:
mail:x:8:
news:x:9:
uucp:x:10:
man:x:12:
proxy:x:13:
kmem:x:15:
dialout:x:20:
fax:x:21:
voice:x:22:
cdrom:x:24:
floppy:x:25:
tape:x:26:
sudo:x:27:
audio:x:29:
dip:x:30:
www-data:x:33:
backup:x:34:
operator:x:37:
list:x:38:
irc:x:39:
src:x:40:
shadow:x:42:
utmp:x:43:
video:x:44:
sasl:x:45:
plugdev:x:46:
staff:x:50:
games:x:60:
users:x:100:coder
nogroup:x:65534:
_ssh:x:101:
podman:x:1002:
```

You also need a custom `/etc/passwd` and (probably) `/etc/group` in `code-server.container`:
```
...

# Image
Image=localhost/code-server-uid-1002:latest

# User
User=1002:1002
# User=podman

# Volumes
Volume=./passwd:/etc/passwd:rw,z
Volume=./group:/etc/group:rw,z
Volume=/home/podman/containers/data/<app>/code-server:/home/coder/.local:rw,z,U
Volume=/home/podman/containers/config/<app>/code-server:/home/coder/.config:rw,z,U
Volume=/home/podman/containers/config/<app>/application:/home/coder/project:rw,z

...
```

Custom `Dockerfile`:
```
# Use Normal Image as Template
FROM docker.io/codercom/code-server:latest

# Set Default UID
ARG CODE_UID=1000

# Set Defalt GID
ARG CODE_GID=1000

# Switch to root User
USER root

# List current User & Permissions
RUN echo "Currently running as User $USER with UID $(id -u) and GID $(id -g)" && \
    echo "Current Permissions for /home/coder:" && \
    ls -lah /home/coder

# Change User ID and Group ID
RUN echo "Set Custom User ID and Group ID" && \
    groupmod --gid=${CODE_GID} coder && \
    usermod --uid=${CODE_UID} --gid=${CODE_GID} coder

# Set Permissions
RUN echo "Set Ownership to ${CODE_UID}:${CODE_GID} for /home/coder" && \
    chown -R ${CODE_UID}:${CODE_GID} /home/coder && \
    echo "Ownership set to ${CODE_UID}:${CODE_GID} for /home/coder"

# (Re)expose Port
EXPOSE 8080

# Change User ID before running Entrypoint
USER ${CODE_UID}

# Run Entrypoint as usual
ENV USER=coder
WORKDIR /home/coder
ENTRYPOINT ["/usr/bin/entrypoint.sh", "--bind-addr", "0.0.0.0:8080", "."]
```

Note: I didn't do this just for the Fun of it ! Setting either `User=podman`, `User=1002:1002` on its own didn't do anything due to some Permission Issues.

Is the base Image NOT having `/home/coder/.config` and `/home/coder/.local`  already existing ? This might be the Reason, as the User running inside the Container with `User=podman` (and custom `/etc/passwd` and `/etc/group`) should be sufficient to have all Access Required, since the bind-mounted Folder is owned by that User (`podman`) on the HOST System.
