### ISSUE TITLE
Can not disable extensions

### ISSUE THREAD

**Issue by aleleba** [coder/code-server#3886]
## OS/Web Information

- Web Browser: Google Chrome
- Local OS: Windows
- Remote OS: Ubuntu
- Remote Architecture: Kubernetes
- `code-server --version`:
- 3.11.0

## Steps to Reproduce

1. Install a extension
2. Disable Extension
3. Reload

## Expected

It should disable extension, and it only shows reload needed

## Notes

This issue can be reproduced in VS Code: Yes/No

**Comment by jsjoeio** [comment]
That's an unusual bug 🤔 I wonder what is causing that. Either way, I was able to reproduce. Thanks for filing! We'll investigate. 

## Video

https://user-images.githubusercontent.com/3806031/127899056-4b86aa71-3e0a-4f04-af73-c10db4fd0c91.mov



## How it works in VSCode


https://user-images.githubusercontent.com/3806031/127899038-003984d4-88ba-4fdb-b079-1419900aaaa6.mov

**Comment by neupsh** [comment]
I have the same issue with code-server running on my unraid (linux-server container). Please let me know if I can help with any logs/data points.

**Comment by neupsh** [comment]
BTW, disabling extension works on 3.9.3 version and not one any versions after that. I have currently downgraded to 3.9.3 to be able to support my workflow.
I am not able to use the latest one since I have workflow where I have multiple extensions that conflict with each other for different workspaces and they work currently by enabling only the ones needed for workspace and disabling the rest.

**Comment by jsjoeio** [comment]
Thanks @neupsh! When we get to this, we may ping you. Good to know it works in 3.9.3. It's possible we accidentally removed something related to this when we upgraded VSCode previously.

**Comment by neupsh** [comment]
hi @jsjoeio is there any update on this issue?

**Comment by jsjoeio** [comment]
@neupsh can you try using the latest version of code-server (3.12.0) and letting me know if you still experience this?

**Comment by neupsh** [comment]
@jsjoeio, yes, it is still same with latest version (3.12.0). After disabling the extension if you click on `Reload Required` button, it reloads the workspace but the extension is still enabled and it still says `Reload Required`.

This issue is preventing me from upgrading and using latest versions of both the code-server and the extensions :(

**Comment by jsjoeio** [comment]
Hmm...I just tested now and I'm not able to reproduce _exactly_. The extension does say `Reload Required` but it is disabled.

Is this the same behavior that you're experiencing? 

https://user-images.githubusercontent.com/3806031/135926995-931e8f9b-6103-4984-b4fc-c60196a575d1.mov

> This issue is preventing me from upgrading and using latest versions of both the code-server and the extensions :(

Do you mind elaborating on that? What's stopping you from upgrading and using extensions? (it is annoying, I agree, but code-server + extensions are still usable, unless I'm misunderstanding something)?

**Comment by neupsh** [comment]
> Hmm...I just tested now and I'm not able to reproduce exactly. The extension does say Reload Required but it is disabled.

ah! let me try that again this weekend and see if the issue is only cosmetic. 

> Do you mind elaborating on that? What's stopping you from upgrading and using extensions? (it is annoying, I agree, but code-server + extensions are still usable, unless I'm misunderstanding something)?

Sure. Most of the extensions work fine and I can keep them enabled but some extensions I use conflict with each other so I use one in one workspace and the other in other workspaces. (Example: [Markdown shortcuts](https://github.com/mdickin/vscode-markdown-shortcuts) vs [Dendron's version](https://open-vsx.org/extension/dendron/dendron-markdown-shortcuts) of the same addon. or [Markdown Notes](https://open-vsx.org/extension/kortina/vscode-markdown-notes) vs [Dendron's fork](https://open-vsx.org/extension/dendron/dendron-markdown-notes) 
Also, another reason is that I want some of the installed extensions (like [dendron](https://open-vsx.org/extension/dendron/dendron)) disabled by default and only enable in one particular workspace.

**Comment by jsjoeio** [comment]
> ah! let me try that again this weekend and see if the issue is only cosmetic.

No worries, let us know!

> but some extensions I use conflict with each other so I use one in one workspace and the other in other workspaces. 

Ahh got it! Well if it works as it is for me, then it should be fine. They should disable just fine (though the UI might have annoying "Reload Required").

After you test, let us know!

**Comment by neupsh** [comment]
@jsjoeio you are absolutely right. The extensions seems to be disabled and the issue only seems to be cosmetic. I am going to keep using the newer version now. Thank you.
