### ISSUE TITLE
Document how to use Python & Jupyter

### ISSUE THREAD

**Issue by AyaanZaveri** [coder/code-server#4333]
1. First, add these lines to your **Dockerfile** to install [Miniconda/Anaconda](https://www.anaconda.com/):

``` 
RUN curl -sfLO https://repo.anaconda.com/miniconda/Miniconda3-py39_4.9.2-Linux-x86_64.sh \
 && /bin/bash Miniconda3-py39_4.9.2-Linux-x86_64.sh -b -p /root/miniconda \
 && PATH="/root/miniconda/bin:$PATH" \
 && conda install -c anaconda jupyter
```

2. Then, install the [**Python Extension**](https://marketplace.visualstudio.com/items?itemName=ms-python.python) and make sure it comes with the [**Jupyter Extension**](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter) or you can add this line to your **Dockerfile**:

```
RUN code-server --install-extension ms-python.python
RUN code-server --install-extension ms-toolsai.jupyter
```

3. Next, in Code-Server create a file with the extension **.ipynb** like **main.ipynb** and set your Python Interpreter as the location of miniconda (~/miniconda/bin/python).
4. Finally, you can add your python code to the file and it should work perfectly.
![Screen Shot 2021-10-09 at 6 35 56 PM](https://user-images.githubusercontent.com/63752541/136675339-f308a4ed-2462-4ff3-800d-0d1508c9985b.png)
![Screen Shot 2021-10-09 at 6 36 52 PM](https://user-images.githubusercontent.com/63752541/136675349-11bbc099-4db2-4bf6-8483-97964737b4c4.png)

If this doesn't work use the **Dockerfile** from https://github.com/cdr/code-server/issues/3199#issuecomment-828745169

**Comment by edvincent** [comment]
@jsjoeio I finally got around to read your (great!) worklog in https://github.com/cdr/code-server/issues/3874 and I'm not sure we fixed the original root-cause, which is still what @0x0L is seeing here?

As in, I think the problem you fixed with https://github.com/cdr/code-server/pull/4231 was a change on the API itself for the future versions of vscode (as it was the insider's version).

The current root-cause still is that the `ms-toolsai.jupyter` scraped and exposed in the default gallery of code-server (https://storage.googleapis.com/vscode-extension-assets/vscode-extensions/vscode/ms-toolsai/jupyter/2021.8.12/Microsoft.VisualStudio.Services.VSIXPackage) is missing the extension itself, as the `out/` folder is missing some nested folder:
* `out/client_renderer/` exists.
* `out/client/` is missing, which is actually where some of the code is - and the error that we are seeing?

Unless moving to Open VSX (https://github.com/cdr/code-server/pull/4319) will indeed come with 3.12.1 (and even depending on the release date), there likely still is some work to do to ensure the extension vended in code-server's current gallery is complete...

I would recommend to re-upload a working extension to code-server's VSX gallery, either by taking it from Open VSX or GitHub, or building it locally? I'm happy to provide a version that I'd build myself so you can upload it?

@0x0L As per [the matrix I created here](https://github.com/cdr/code-server/issues/3874#issuecomment-923383398) the only working version of `ms-toolsai.jupyter` are the ones downloaded from Open VSX or GitHub build artifacts. The ones vended by the current gallery won't work.

If you don't want to completely switch to Open VSX, I reckon the following should work in a Dockerfile - just to install the extensions?

```
RUN SERVICE_URL="https://open-vsx.org/vscode/gallery" ITEM_URL="https://open-vsx.org/vscode/item" code-server --install-extension ms-python.python
RUN SERVICE_URL="https://open-vsx.org/vscode/gallery" ITEM_URL="https://open-vsx.org/vscode/item" code-server --install-extension ms-toolsai.jupyter
```
