### ISSUE TITLE
[Feat]: Add VS Code version number to --version output

### ISSUE THREAD

**Issue by jawnsy** [coder/code-server#4874]
## What is your suggestion?

The `code-server` version output shows the version of `code-server` itself:

```
$ code-server --version
4.0.2 5cdfe74686aa73e023f8354a9a6014eb30caa7dd
```

It is possible to get the corresponding (embedded) VS Code/code-oss-dev version using the `--json` output:

```
$ code-server --version --json
{"codeServer":"4.0.2","commit":"5cdfe74686aa73e023f8354a9a6014eb30caa7dd","vscode":"1.63.0"}
```

It would be convenient to also have the VSCode version in the --version output.

## Why do you want this feature?

This makes the VS Code version more discoverable, which is useful when evaluating the versions of extensions that are compatible.

## Are there any workarounds to get this functionality today?

Yes, users can run `code-server --version --json` and look at the output. But JSON output is not as human-readable.

## Are you interested in submitting a PR for this?

Sure, would like a pointer to the code though.

**Comment by jsjoeio** [comment]
Fantastic idea! This is where the code lives in `entry.ts`:

https://github.com/coder/code-server/blob/94f378c1960a2b8df4da70fb900f6cfec0191982/src/node/entry.ts#L40-L54

I don't think we have a file yet called `entry.test.ts` so you could create one if you're comfortable adding a test as well (if not, I'm happy to).

Otherwise, you could add another test to our standalone release here:

https://github.com/coder/code-server/blob/94f378c1960a2b8df4da70fb900f6cfec0191982/ci/build/test-standalone-release.sh
