### ISSUE TITLE
release: v4.2.0

### ISSUE THREAD

**Issue by code-asher** [coder/code-server#4942]
## Checklist

- [x] Assign to next release manager
- [ ] Close previous release milestone
- [ ] Create next release milestone
- [ ] Associate issue with next release milestone

**Comment by nooobcoder** [comment]
@code-asher I am on a raspberry Pi, and using docker to run code-server. 
These are the error trace on the latest release of code-server.
This needs to be solved tried many times, fixing permissions too, also did not bind any volume to `~/.local/share/code-server` to make volume itself (ephemeral volume of container).
Sadly, the code-server releases on `arm` is very buggy since the latest releases. The team needs to look deeply into it.

![image](https://user-images.githubusercontent.com/50350828/156693101-532b6fa1-9dd8-4e18-be18-e17b45a0a604.png)

**Comment by jsjoeio** [comment]
@nooobcoder this is the release issue - can you please open a Q and A or a new bug report and we can take a look? Thanks!
