### ISSUE TITLE
[Bug]: dangling links in 4.3.0 release

### ISSUE THREAD

**Issue by skumagai** [coder/code-server#5157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

It's about the release file for macOS.

### Steps to Reproduce

1. Download standalone 4.3.0 for macOS (`code-server-4.3.0-macos-amd64.tar.gz`) from github
2. Untar the file
3. `find code-server-4.3.0-macos-amd64 -xtype l`

### Expected

No output/dangling link

### Actual

```
code-server-4.3.0-macos-amd64/lib/vscode/extensions/node_modules/.bin/tsc
code-server-4.3.0-macos-amd64/lib/vscode/extensions/node_modules/.bin/tsserver
```

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

First, I'm not sure if this is a bug. If not, feel free to close this issue.

I was working to make 4.3.0 available as a conda package in conda-forge/code-server-feedstock#62, and I noticed a build was failing on macOS due to dangling links (see: [CI pipeline](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=492751&view=logs&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b).

Manually unpacking 4.3.0 release for macOS confirms that `lib/vscode/extensions/node_modules/.bin/{tsc,tsserver}` are pointing to nonexistent `../typescript/bin/{tsc,tsserver}` (`../typescript/bin` directory doesn't exist).

Since I don't code in Javascript and Typescript, I can't asses if this has any impact or not. Nevertheless, I thought it might be good to let you know about it.

**Comment by code-asher** [comment]
The dangling links happen because Code removes some files in its
postinstall but it does not remove the associated .bin links.

https://github.com/microsoft/vscode/blob/d976637473418766ee0610294fdf820a2dfded62/extensions/postinstall.mjs

We had problems with these dangling links when packaging the deb and rpm
via nfpm so we added some code to remove them but we only do it for the
nfpm step and not for the standalone releases!

So we should take this code:
https://github.com/coder/code-server/blob/ef0d76bc16fad89ae951a94d616d41f0ab3bed57/ci/build/build-packages.sh#L53-L56

And move it here:
https://github.com/coder/code-server/blob/ef0d76bc16fad89ae951a94d616d41f0ab3bed57/ci/build/build-standalone-release.sh#L31

Of course an even better solution would to be to submit a patch
upstream. :)

**Comment by code-asher** [comment]
I think maybe these are gone now but I need to check.

**Comment by ACMCMC** [comment]
Still getting this error on current releases (e.g. `code-server-4.97.2-linux-amd64.tar.gz`). Any ideas? :)

**Comment by code-asher** [comment]
What error are you seeing?  This issue describes some dangling links but not any errors that I could find.

As for the links, I am not seeing any danging in `code-server-4.97.2-linux-amd64.tar.gz`.

```
$ mkdir /tmp/test
$ curl -L https://github.com/coder/code-server/releases/download/v4.97.2/code-server-4.97.2-linux-amd64.tar.gz | tar -xzC /tmp/test
$ find /tmp/test/code-server-4.97.2-linux-amd64 -xtype l
```
