### ISSUE TITLE
[Bug]: Jupyter not working with this version of code-server

### ISSUE THREAD

**Issue by camelator** [coder/code-server#5178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Firefox
- Local OS: Ubuntu 20.04
- Remote OS: Ubuntu 20.04
- Remote Architecture: ARM
- `code-server --version`: latest : 4.4.0
- 

### Steps to Reproduce

1. install the latest python plugin
3.Check Jupyter Version and try to upgrade to the latest
4

### Expected

I expect to be able to install the latests versions of plugins.

### Actual

Unfortunately, Code-server propose several versions to install but the latest is not available (at least 2022.4.xx)
=> Jupyter can not be used as there is a bug on the previous versions at python kernel initialisation

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

This bug does not happen with the standard vs code : the latest plugins are available

**Comment by jsjoeio** [comment]
> Unfortunately, Code-server propose several versions to install but the latest is not available (at least 2022.4.xx)
=> Jupyter can not be used as there is a bug on the previous versions at python kernel initialisation

code-server uses the Open VSX marketplace so if the version you want isn't available then it isn't available in Open VSX. 

When I install the Python extension, it installs v2022.4.1 and Jupyter v2022.3.1000752054 and it appears to be working. 

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/3806031/167500285-539b09aa-a381-49dc-8f1a-d358c2e4b9b1.png">

Unless I'm missing something else, I don't think there is much we can do about this.

**Comment by camelator** [comment]
Definitely, it does not work.
for plugin Python, according to this page https://open-vsx.org/extension/ms-python/python/changes
the last version looks like 2022.6.1 and  I can only install 2022.4.1

**Comment by jsjoeio** [comment]
Based on [this](https://github.com/microsoft/vscode-python/blob/release-2022.6/package.json#L45), I assume the version you're trying to install requires a newer version of VS Code. I don't think it will work because of that. Once we upgrade VS Code in code-server and cut a release, then it will work. Until then, you should use an older version like the one I showed working.

**Comment by Newtoniano** [comment]
Jupyter notebook is still not working for me, even when I try to install the specific version that is suggested as working fine. Anyone has any idea what's the cause and if there's a workaround?

**Comment by ab2dridi** [comment]
Hello,

Same issue here,  i'm getting this issue when trying to install Jupyter Extension 

code-server --version: 4.7.1 77bbed48315a7cc275dc05a53d197197928f4b88 with Code 1.71.2
Jupyter extension version: ms-toolsai.jupyter-2022.10.1102891042.vsix

The error

Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.71.2'.

i tried a lot a different versions of Jupyter extension, same error

**Comment by jsjoeio** [comment]
It's possible they updated it to require Code 1.72.2. Older versions should work 🤔

How are you both installing the extension? CLI or via the Extensions panel inside code-server?

**Comment by ab2dridi** [comment]
I tried yet older versions but same thing, not working
I install it using cli

**Comment by jsjoeio** [comment]
What happens if you try installing it via the UI i.e. inside code-server?

**Comment by groldo** [comment]
Hello,

i have a code-server setup:
with a Dockerfile

```Dockerfile
FROM codercom/code-server:4.12.0

RUN sudo apt-get update && sudo apt-get -y install --no-install-recommends python3-venv python3-pip

RUN code-server --install-extension ms-toolsai.jupyter
RUN code-server --install-extension ms-python.python
```
and a compose file

```yaml
version: "3"
services:
  code:
    build: .
    ports:
      - 8080:8080
```

<img width="1433" alt="code" src="https://user-images.githubusercontent.com/61418774/234662083-f15fe669-9c34-443f-b050-b7af022d0ad8.png">

I've tried a lot of different combinations of code extension versions.
None of them gave a different result.

I have the same kind of setup but with code-server  4.0.1

```Dockerfile
FROM codercom/code-server:4.0.1
[...]
```

with `4.0.1` python cells gets rendered correctly, 
but markdown cells doesn't get rendered correctly

<img width="1435" alt="code-server-4.0.1" src="https://user-images.githubusercontent.com/61418774/234664724-30459226-fa40-464b-8adf-8fdb6d2081df.png">

In `4.0.1` the jupyter notebook renderer extension doesn't get installed because it is not compatible with code-server,
which makes me think that this issue has something to do with the  jupyter notebook renderer extension

**Comment by code-asher** [comment]
I built and ran your Dockerfile but strangely it worked for me.  Maybe somehow a browser cache issue?

![ipynb](https://user-images.githubusercontent.com/45609798/235505662-d9408b91-8874-4d15-b55d-35f84d86e78c.png)

**Comment by groldo** [comment]
Thanks for your feedback it was quite valuable. The cache guess was a miss, but I came up with another browser, in my case a safari, which does worked. And when I was giving firefox another try I saw that uMatrix was blocking some needed domains. When I allowed access to this domains everythings worked like a charm.
So I can confirm above scenario does work.

**Comment by code-asher** [comment]
Ahhhh that makes sense!
