### ISSUE TITLE
[Feat]: Upgrade to vscode 1.69

### ISSUE THREAD

**Issue by balajib-b** [coder/code-server#5344]
## What is your suggestion?
Upgrade to vscode 1.69.1

**Comment by jsjoeio** [comment]
I think 1.69.2 is out now so I changed title to major.minor to count for both

**Comment by bala** [comment]
@code-asher @jsjoeio we are always 1 minor release behind the vscode. currently, we are in 1.68 while vscode is in 1.69. by the time aug 2022 is released, vscode may move to 1.70. Can we have an intermediate upgrade release closest to vscode release schedule? The vscode upgraded release may help resolve some issues in our existing issues list as well as submit any new bugs. since it is only users option to install upgrade, interested users will install and let us know any new bugs. this will also keep us close to vscode release schedule and help us tryout the same features in vscode desktop.

**Comment by jsjoeio** [comment]
@bala yeah, you're right. I mean we're trying as best we can to keep up but it's been very tough lately. We're at a company off-site this week for example.

@code-asher and I can discuss this with @misskniss @tjcran to see how we can improve our VS Code upgrade and release cadence to be more in line with upstream. Thanks for the suggestion!

**Comment by benz0li** [comment]
vscode 1.70 is out: https://github.com/microsoft/vscode/releases/tag/1.70.0

**Comment by balajib-b** [comment]
#5417 is opened separately

**Comment by fritterhoff** [comment]
First patches for 1.70 #5422 look good. Jupyter, `code-server` in cli look fine. More must be checked the next days...

**Comment by jsjoeio** [comment]
Completed via https://github.com/coder/code-server/pull/5422
