### ISSUE TITLE
[Feat]: Open with coder/ selfhosted code-server button in readme.md files

### ISSUE THREAD

**Issue by bala** [coder/code-server#5371]
## What is your suggestion?
Can we have a button in github/gitlab repos - similar to  open with colab or open with gitpod
## Why do you want this feature?
this will enable one click access to open repos in coder/self hosted code servers
## Are there any workarounds to get this functionality today?
not that i am aware of
## Are you interested in submitting a PR for this?
i need some development support to implement this

**Comment by jsjoeio** [comment]
Are you asking for an image for that button that you can use in your markdown files?

**Comment by bala** [comment]
@jsjoeio can we create an option in code server which will enable the user to open any repo open in the code server in one click.

The idea is to avoid using the command line git clone. 

There should be an open with  code server button (similar to open with gitpod) which will clone repo and open it in the currently signed in code server login.  

If the repo is public then it should clone and open the corresponding folder. If its private we can use some API token to connect gthub, gitlab, bitbucket  and then get the repo authenticated. 


This will be a big feature to code server.

Note: gitpod has this functionality. I wish our code server has it too.

**Comment by jsjoeio** [comment]
So this is what Gitpod's looks like

```markdown
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/PragatiVerma18/Snippet-Share])
```
rendered: 
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/PragatiVerma18/Snippet-Share])

it's really nice but the problem is...code-server is self-hosted. we don't have a hosted version. We could add a query param like `?cloneRepo=coder/coder-server` that you could use in your own repos?

I don't know if that would help much.

What are your thoughts?

**Comment by bala** [comment]
it makes sense that we are using self-hosted instances on different domain names.
