### ISSUE TITLE
[Feat]: Extension gallery popup window

### ISSUE THREAD

**Issue by bala** [coder/code-server#5411]
## What is your suggestion?
In order to try out any other marketplace sources, we need to set export SERVICE_URL option in cmd or bashrc file. can we have a popup menu that will ask for serviceURL, itemURL, cacheURL.
## Why do you want this feature?
each time we switch between market place we have to set export option and restart code server instance to pickup new URL. if we can have a popup menu or settings page where this can get loaded without having to stop and restart code-server. this reload kills the current jobs. a hot swap instead of restarting will be a super option.
## Are there any workarounds to get this functionality today?
set export options in command line or bashrc and reload the whole instance of code-server
## Are you interested in submitting a PR for this?
No

**Comment by code-asher** [comment]
I think we should not do this, because it will be a lot of patching.  VS Code assumes one marketplace and we would have to thread that through in all sorts of places and it would probably get pretty nasty.

Also, even restarting code-server with a new marketplace is janky because extensions do not seem to be cross-compatible, so it breaks things like updates.

We could try asking about this upstream but they seem opposed to any changes that make it easier to swap out the marketplace.
