### ISSUE TITLE
[Testing]: fix flakey state collisions test  

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#5482]
https://github.com/coder/code-server/runs/7927112771?check_suite_focus=true#step:12:236

State collisions test has been flaking. I'd like to see if we can make this more stable.

cc @code-asher in case you have any ideas!

**Comment by code-asher** [comment]
So to recap the issue: we need to wait for a database write but but have no way of telling when it actually writes so we wait before reloading the page and just hope it wrote in time.  Sometimes it does, sometimes it does not.

The ideal solution would be event-based.  We could patch an event in that we can then listen for in our tests.  I was reluctant to add more patching just for the tests but this is probably fine.  There is an existing `BroadcastChannel` I was looking at but if I recall correctly it only fired events for one of the databases which was not the workspace one.  But possibly we could modify that.

Another idea is to poll the database to see if the value we want has been written yet.

Last idea is to drop the migration entirely since it has been about six months since 4.0.2 which has hopefully been enough time.  If someone has not upgraded the consequence is that they will to re-open any files they had open.

**Comment by jsjoeio** [comment]
> Last idea is to drop the migration entirely since it has been about six months since 4.0.2 which has hopefully been enough time. If someone has not upgraded the consequence is that they will to re-open any files they had open (and maybe some other state like the opened terminals).

I personally would vote for this one since it would reduce our patch count and allow us to remove the tests. Let's revisit next month and make a decision.

**Comment by jsjoeio** [comment]
> > Last idea is to drop the migration entirely since it has been about six months since 4.0.2 which has hopefully been enough time. If someone has not upgraded the consequence is that they will to re-open any files they had open (and maybe some other state like the opened terminals).
> 
> I personally would vote for this one since it would reduce our patch count and allow us to remove the tests. Let's revisit next month and make a decision.

Talked offline and decided to go with this approach
