### ISSUE TITLE
[Docs]: Coder vs. Code Server?

### ISSUE THREAD

**Issue by aghasemi** [coder/code-server#5508]
Hi,

I have been using code server for some time and am quite happy with it (thanks). 

Recently a new open source product has been released by the team, called coder. 

I was wondering how these two are different. There is only a table which says coder is a Platform vs. code server being an IDE :-/

Is there any document etc... that I can read about it? And can I/does it make sense to run both coder and code server on the same VPS? Is coder _heavier_ and/or a superset of code server?

Many thanks

**Comment by jsjoeio** [comment]
Great question! We have a small note in the readme:

> Note To manage code-server for a team on your infrastructure, see: [coder/coder](https://cdr.co/coder-github)

From my view, code-server works well for individual users and coder has a lot of features for teams. You could certainly use coder as an individual! 

But this still could be a great addition to the docs 🤔

cc @bpmct @thealidev any thoughts?

**Comment by thealidev** [comment]
Best web IDE is not code server because it is self hosted with many issues
  
Best web IDE is Replit
  
Btw cider and code servers are good env for closed source projects
  
So my though is for open source use replit and github
  
And for closed source use coder and code server

**Comment by aghasemi** [comment]
Maybe a point that would be nice to clarify, is whether Coder and Code Server will be developed and maintained in the foreseeable future, with new features, VSCode version, extensions, etc... coming to _both_ at about the same time, or one (coder?) will be prioritised?

**Comment by jsjoeio** [comment]
Great point!

So [Coder](https://github.com/coder/coder) uses code-server in most templates/workspaces. That means it's reliant on code-server. Our plans right now for code-server are to continue maintaining it and keeping it up to date with VSCode as quickly as we can!

code-server will always get the updates first but that's because VS Code is _part_ of code-server. Coder (coder/coder) will get it with each code-server release since it's downloads it via the install script.

Hope that answers your question!

**Comment by thealidev** [comment]
If we talk about best free altanitives  
Coder == Jetbrains Space  
Code Server == Replit
