### ISSUE TITLE
[Feat]: --app-name across the app

### ISSUE THREAD

**Issue by tobycm** [coder/code-server#5935]
## What is your suggestion?

 #5633 this but across the app and not just Login/Error page

## Why do you want this feature?

Would be nice to customize "code-server" on the titlebar to something else of my choice

## Are there any workarounds to get this functionality today?

I don't know

## Are you interested in submitting a PR for this?

I'll try

**Comment by jsjoeio** [comment]
I think we'd need to decide if this is something we want to support. cc @code-asher 

I can see both sides personally.

**Comment by code-asher** [comment]
Personally I think if someone is wanting to rebrand code-server they could repackage with an edited `product.json`.  And if there was effort to make this dynamically customizable I think it should go upstream rather than a patch in code-server.

**Comment by npenin** [comment]
This is apparently already covered in many places like https://github.com/coder/code-server/blob/c995988b70e4134dacfa98a8ae0af2b05c6cd7b6/src/node/routes/vscode.ts#L51. Not sure why this is not working yet though.

**Comment by code-asher** [comment]
That particular change has not been released yet.

**Comment by code-asher** [comment]
This is released, but let me know if there are places we missed.

**Comment by TheZoker** [comment]
@code-asher 
I think the default title if no file is open still does not use the `app-name`, right?

![image](https://github.com/coder/code-server/assets/1368405/2ddf2558-7c73-4773-a435-69aae322d859)

I started the application like this:
```
code-server --app-name "VS Code"
```

**Comment by code-asher** [comment]
Oh yeah, looks like you are right.  We should add a new template variable for the HTML files.

**Comment by mallport** [comment]
@code-asher Any plans for this?

**Comment by code-asher** [comment]
No plans from our end at the moment, but happy to take PRs.

**Comment by MalteHei** [comment]
I just stumbled upon this issue while troubleshooting why the code-server window title did not contain the name I set via `--app-name`.
The VSCode settings supported my assumption that `--app-name` is propagated to VSCode because of the placeholder with the same name (`${appName}`, which is hard-coded to `code-server` currently?).

I think this issue should be reopened.

**Comment by MicahZoltu** [comment]
I run a code-server instance in a container for each repository for isolation/sandboxing.  At the moment this means I have a lot of tabs in my browser that all have the same name.  I would like to have them each named based on the name of the container/repository so I can distinguish them easily rather than having to guess which one is which.  Everything online seemed to suggest that `--app-name` was the solution, which seemed perfect, but alas it doesn't actually solve this problem.

**Comment by code-asher** [comment]
Opened https://github.com/coder/code-server/issues/7688 for this
