### ISSUE TITLE
[Feat]: Upgrade Vscode to 1.76

### ISSUE THREAD

**Issue by balajib-b** [coder/code-server#6050]

**Comment by benz0li** [comment]
@code-asher Will there be a "March 2023" milestone?

**Comment by benz0li** [comment]
[vscode 1.76.1](https://github.com/microsoft/vscode/releases/tag/1.76.1) has been released:

> @code-asher Consider taking a `.2`-release as base for a new code-server release.  
> ℹ️ `.0`-releases have had some fundamental bugs.
> 
> i.e.
> 
> 1. use the `.1`-release as base for a _release candidate_ (RC)
> 2. test, debug and fix; maybe do another RC-release
> 3. update codebase to the `.2`-release
> 4. test, debug and fix
> 5. release

– https://github.com/coder/code-server/issues/6004#issuecomment-1425355890

**Comment by code-asher** [comment]
Sorry all, I was unexpectedly out last week.

Joe is no longer involved, at least as a maintainer (his farewell is here for those interested: https://github.com/coder/code-server/discussions/6031).  

Maintenance falls to me and while we do have a vested interest in keeping code-server updated since we use it ourselves I think it is unlikely we will do much more than update VS Code and handle any PRs that folks might open.

If we had more activity I think grooming milestones would make sense but since there will only be VS Code updates I am not sure it makes sense to spend the effort.

I will try to get us updated today.

**Comment by benz0li** [comment]
> Maintenance falls to me and while we do have a vested interest in keeping code-server updated since we use it ourselves I think it is unlikely we will do much more than update VS Code, handle any PRs that folks might open, and triage issues/discussions.

@code-asher Thank you for the clarification. I am satisfied with the current features (base path, local storage, proxy url, etc.) and keeping the software up to date is fine with me.
