### ISSUE TITLE
Loading custom key bindings for code-server

### ISSUE THREAD

**Issue by indoben** [coder/code-server#6324]
Referencing the instructions found here: [link](https://coder.com/blog/using-custom-vs-code-keyboard-shortcuts-with-coder)

I added the following lines to my startup script

```shell
    mkdir -p /home/coder/.local/share/code-server/User
    echo '[{"key": "ctrl+enter", "command": "workbench.action.terminal.runSelectedText"}]' > /home/coder/.local/share/code-server/User/keybindings.json
```

However, even after a full restart, the file appears where expected, but it is not being picked up by code-server. Is there a newer approach since this documentation was written?

**Comment by code-asher** [comment]
Yeah all configuration will be located in the home directory of 
the user that launched code-server by default.  That blog post 
would likely be better off using ~ instead of /home/coder.

I believe our own documentation always references ~ but if you 
have ideas on where to improve the documentation then suggestions 
and PRs are welcome!
 
Just as an aside, you probably already know this but launching as 
root could be risky, depending on how you have things set up.
