### ISSUE TITLE
[Bug]: opening terminal opens a new tab

### ISSUE THREAD

**Issue by 404invalid-user** [coder/code-server#6333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: samsung internet
- Local OS: android 11
- Remote OS: proot debian
- Remote Architecture: arm64
- `code-server --version`: 4.14.1 5c199629305a0b935b4388b7db549f77eae82b5a with Code 1.79.2

### Steps to Reproduce

1. setup code server
2. open code-server in the browser or PWA
3. click hamburger menu > terminal > new terminal (or use shortcut) 

### Expected

the terminal window opens

### Actual

the terminal window opens but a seccond later a new tab will open to https://localhost:8080?ew=true but in the case of a WPA it woould open a web view then it just relaunches the app with the terminal closed.

### Logs

i found nothing of intrest i can provide the whole log if you want

### Screenshot/Video

https://github.com/coder/code-server/assets/68563978/52844bb6-dc2e-4939-8b9a-7fba858aaafa

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment]
Strange, I tried to reproduce on an Android phone but a new tab is 
not opening for me.  Does this reproduce outside of Android for 
you or is it Android-only?

This definitely does not reproduce on Codespaces for you?

The only time I have seen ew=true is when the workspace is being 
closed (File > Close Folder from the hamburger menu or "Close 
Workspace" from the command palette) so maybe that is being 
triggered somehow but I have no idea how.  And it is supposed to 
open in the same tab, not a new tab, so that is also weird.

Have you configured any settings?  Maybe it only triggers with 
certain settings.

**Comment by 404invalid-user** [comment]
Sorry for taking a while, yes I can reproduce it in ios and double checked codespace and it does not do this also no it's a fresh install

**Comment by code-asher** [comment]
I wonder if it is something fixed in the latest VS Code.  We will 
be making a new release soon (maybe today) with the same version 
that Codespaces is using so we should test again once that happens 
(or you can build the repository if you want to test now).

**Comment by 404invalid-user** [comment]
ah awesome i will try that now

**Comment by 404invalid-user** [comment]
it looks like that has fixed it
