### ISSUE TITLE
[Bug]: Unable to paste - CMD+V. Macbook Pro M1 Max

### ISSUE THREAD

**Issue by sneighbors** [coder/code-server#6452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:
- Local OS: 13.4 (22F66)
- Remote OS: Home Assistant 2023.9.3
- Remote Architecture:
- `code-server --version`: 
code-server: v4.16.1
Code: 1.80.2
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Date: 2023-07-31T17:15:21.760Z (1 mo ago)
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2023.4 (io.robbie.HomeAssistant; build:2023.460; macOS 13.4.0) Mobile/HomeAssistant, like Safari

### Steps to Reproduce

1. Open code-server
2. type some text
3. highlight text
4. cmd-x (cut the text)
5. cmd-v (paste the text) Nothing happens
6.
7.

### Expected

The text that was cut in step 4 should have been pasted

### Actual

Nothing happens and the right click menu does not show a paste option

### Logs

Not available from within Home Assistant from what I can tell

### Screenshot/Video

<img width="436" alt="image" src="https://github.com/coder/code-server/assets/1434088/5c45d31e-d56d-4509-9214-ae5d0c7577d4">

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

This is the port that is used with in Home Assistant maybe due to updated HA Code version that was installed as I was thinking this was working before.

**Comment by code-asher** [comment]
Sorry for the long delay for triaging.  Does Home Assistant pull in code-server through an iframe?  Do you see any error logs in the browser console?  I wonder if it is missing the `allow` to make the clipboard API work.

**Comment by code-asher** [comment]
Ahh yeah browsers only allow access to the clipboard API over secure contexts; as a tangent we need to remove that wishy-washy popup and show a more concrete message when there is actually a failed attempt to use APIs restricted by the browser.

I think they must have reworked things not to use the clipboard API, because I experimented a bit just now and even after disabling the clipboard API copy/paste is still working for me, and I am pretty sure that was not always the case.
