### ISSUE TITLE
[Bug]: AUR package publishing no longer works

### ISSUE THREAD

**Issue by somebody1234** [coder/code-server#6712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

Remote OS: Arch Linux (Artix)

### Steps to Reproduce

1. `paru -S code-server` or `yay -S code-server`
2. open `code-server`
3. notice the popup saying that a new version is available

### Expected

Latest version is available

### Actual

Latest version is 4.21.0

### Does this issue happen in VS Code or GitHub Codespaces?

- [ ] I tested this in native VS Code.
- [ ] This does not happen in native VS Code.
- [ ] I tested this in GitHub Codespaces.
- [ ] This does not happen in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

### Notes

See: https://github.com/coder/code-server/actions/workflows/publish.yaml

**Comment by somebody1234** [comment]
i guess it's *technically* not a bug in the package itself...

**Comment by code-asher** [comment]
Yeah I have been putting this off because we had plans to redo the AUR publishing and move it all into this repository instead of using a separate repository, but that might still be a long ways off so we should probably fix this.

Looks like the issue is because the author changed their username so we just need to update the action.  https://github.com/heyhusen/archlinux-package-action/issues/41

**Comment by code-asher** [comment]
Fixed, and published 4.22.0 to the AUR.
