### ISSUE TITLE
[Bug]:  Enhancing Connection Stability Between Code-Server and JupyterHub Using Jupyter Extension and Token Authentication.

### ISSUE THREAD

**Issue by BouarfaMahi** [coder/code-server#6715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:  Chrome 122.0.0.0
- Local OS: windows 10
- Remote OS: Ubuntu 22.04 LTS
- Remote Architecture: amd64
- `code-server --version`: 4.19
- njupyter extension:  v2023.9.100

### Steps to Reproduce

open code-server
install extension
connect to jupytherHub
run a notebook

### Expected

No disconnection.

### Actual

Hello, I am using the Jupyter extension because I need it to connect a code-server to a JupyterHub instance using a token.  Please let me know how the connection stability can be improved, as I sometimes experience disconnects. Is there any log to check?

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I tested this in native VS Code.
- [ ] This does not happen in native VS Code.
- [ ] I tested this in GitHub Codespaces.
- [ ] This does not happen in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

**Comment by code-asher** [comment]
You might need to ask in the extension repository because the connection happens from the extension, right?  I am not sure where they put their logs but usually there is a dropdown for a plugin's log in the output tab of the bottom panel (the same one that shows the terminal).  They might have some options you can set for more verbosity.  There is also probably some logging from the JupyterHub instance you could look at, but I have no experience with that.

**Comment by BouarfaMahi** [comment]
Thanks @code-asher
