### ISSUE TITLE
Frequently encountered: Cannot reconnect

### ISSUE THREAD

**Issue by tangweisuper** [coder/code-server#6982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:chrome
- Local OS:macOS
- Remote OS:Ubuntu
- Remote Architecture:docker
- `code-server --version`:4.0.1

### Steps to Reproduce

1.use base image: [linuxserver/code-server] and install python
2.build and run the new image
3.do sth in code server

### Expected

works well

### Actual

Frequently encountering the following problems
![image](https://github.com/user-attachments/assets/449dc0e8-a7bb-4de2-a3ec-9ec00a0d2230)

After clicking reload, this pop-up window will immediately appear again

This problem occurs randomly. Is it a bug? and how to debug

thx

### Logs

```shell
these seems to be relevant

[08:29:09] [241.255.2.110][b1c26811][ManagementConnection] Unknown reconnection token (never seen).
[08:29:10] [241.255.2.110][8a45d19c][ManagementConnection] Unknown reconnection token (never seen).
```

### Does this bug reproduce in native VS Code?

Yes, this is also broken in native VS Code

### Does this bug reproduce in GitHub Codespaces?

Yes, this is also broken in GitHub Codespaces

### Are you accessing code-server over a secure context?

- [x] I am using a secure context.

**Comment by code-asher** [comment]
If it says the token is unknown, that implies the backend restarted.  Did it crash?  Please post the code-server logs from the server if you can.

**Comment by code-asher** [comment]
I will close for now but let me know if you get back to this.

**Comment by logesh-jarvis** [comment]
@code-asher I'm facing this issue with code-server docker image. For me the pods didn't restart, but the pop up is shown and when looking at the logs, I'm getting this log - [ManagementConnection] Unknown reconnection token (never seen).

**Comment by code-asher** [comment]
Hmm as I understand it, that message could only appear if the backend restarted (or if one was to manually type an invalid reconnection token, which is probably not the case here).

Or, at least, I am not seeing anywhere that tokens are deleted, so that implies memory loss due to restart: https://github.com/microsoft/vscode/blob/7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e/src/vs/server/remoteExtensionHostAgentServer.ts#L753-L759

4.0.1 is pretty old, possibly a newer version will work differently, although the logic looks similar between the versions as far as I can tell.
