### ISSUE TITLE
Options for inserting default settings at deployment time that are separate from user settings

### ISSUE THREAD

**Issue by DeepCowProductions** [coder/code-server#6995]
## What is your suggestion and why do you want this feature?
I was not able to find a nice solution for this so far:

Here is the scenario:
I deployed a custom coder-server installment inside JupyterLab.
For different Images and environments, I want to provide each user with different sets of extensions and default settings, that are independent of the workspace that the User are working in inside their container.
The Problem is that the users $HOME directory has to be identical for every kind of image, so a global settings.json in their $HOME is not a great solution. This would also not be easily updated with image releases, where new default settings for extensions might be required.

Technically, the best way (maybe?) would be to provide a set of default settings that originate from the deployment and are not persistent inside the user directories.
VSCode itself does not seem to provide any support for this as default settings are some kind of ephemeral and not stored in any particular location (at least I was not able to find it)

This would also be very useful for modifying the default values for pre-installed extension, such as the python extension.
In particular, this would allow an easy way of defining where the targeted python interpreter is located, which might not be where one would expect it, when a custom env is installed via conda for example.

## Are there any workarounds to get this functionality today?
The best workaround so far is to create a script that creates or merges a settings.json file at the desired location every time the containers starts. But like I said, this file is also user edible and while merging json is not hard, it is unclear what to do with conflicts.

For modifying extension settings, i do something like this as a workaround:
```bash
QUERY='.contributes.configuration.properties."python.condaPath".default="/opt/conda/bin/conda"' \
jq $QUERY /usr/lib/code-server/lib/vscode/extensions/ms-python.python-*/package.json | sponge /usr/lib/code-server/lib/vscode/extensions/ms-python.python-*/package.json \
```
I am not sure whether this also works for internal settings, such config files are also hard to find...

## Are you interested in submitting a PR for this?
Maybe, although I don't know whether such a feature could be implemented nicely given the fact that VSCode itself does not seem to support this. I am however open to other solutions.

**Comment by code-asher** [comment]
Hmm yeah definitely an interesting idea but I think it might be out of scope for patching in code-server.

I know VS Code has setting policy stuff but I think it is Windows-only at the moment.  https://github.com/microsoft/vscode/issues/147756  If that worked on other machines then I think it would fulfill the criteria here.

**Comment by benz0li** [comment]
@code-asher IMHO this is out of scope for patching in code-server.

@DeepCowProductions I use [`/var/backups/skel/.local/share/code-server/User/settings.json`](https://github.com/b-data/jupyterlab-r-docker-stack/blob/f662837738e4f6634b2dd406f10779ae59d18465/base/conf/user/var/backups/skel/.local/share/code-server/User/settings.json) and [`/usr/local/bin/before-notebook.d/30-code-server.sh`](https://github.com/b-data/jupyterlab-r-docker-stack/blob/f662837738e4f6634b2dd406f10779ae59d18465/base/scripts/usr/local/bin/before-notebook.d/30-code-server.sh).

Cross reference:

* https://github.com/jupyter/docker-stacks/issues/1478

**Comment by code-asher** [comment]
Yeah, I agree.  I will go ahead and close this, anyone interested in an official solution please follow the upstream issue.

**Comment by MicahZoltu** [comment]
The upstream issue was resolved, but unfortunately VSCode disables policies (the partial solution to the problem) for VSCode Web.  Would it be reasonable to make policies apply to code-server?

https://github.com/microsoft/vscode/issues/27972 is still open, but it would be nice to at least get the policy stuff over to code-server.

While I was trying to hack around this locally my AI coding assistant narrowed down to what it thinks the problem is (and which seems like a reasonable guess), which is that the `ConfigurationService` that is instantiated for the electron app includes a `policyService`
https://github.com/microsoft/vscode/blob/main/src/vs/code/electron-main/main.ts#L226
But the configuration service that is instantiated for VSCode Server uses a `NullPolicyService`.
https://github.com/microsoft/vscode/blob/main/src/vs/server/node/serverServices.ts#L145

Of note, the policy service on Linux is just a JSON file in a particular location, which I think would all that would be needed here.

In theory, the only patch necessary to fix this for code-server would be to change VSCode Server to instantiate a policyService and use it.  I suspect that reality is quite different from theory, as always, but this feels like it has potential to be a low-lift improvement.

**Comment by code-asher** [comment]
Yeah if there is a relatively simple way to patch this to make it work for web I feel like it would be worth maintaining here in code-server, if the VS Code team declines to merge it.
