### ISSUE TITLE
Making folder and file path user's path in code server

### ISSUE THREAD

**Issue by Muhammed-20** [coder/code-server#7048]
## What is your suggestion?

* I want the folder and file path on the code server to be made the user's path.

## Why do you want this feature?

* I want the folder and file path on the code server to be made the user's path.  @jpinnix 

## Are there any workarounds to get this functionality today?
* No

## Are you interested in submitting a PR for this?
* No

**Comment by code-asher** [comment]
Could you expand on this?  If you want to open the user's home directory or something, you can add `?folder=/home/user` to the URL, is that what you mean?

**Comment by code-asher** [comment]
Oh wait I see the discussion you opened.  When you open a file there should be a "show local" button you can use to browse local files.  Let me know if you have issues with it.

But, there is no way to open a local folder.  I think this is probably an upstream limitation, since Codespaces has the same behavior, so we would need to open an issue upstream to change this.
